---
- name: Create iSCSI-B Portgroup - '{{ iscsi_b_portgroup }}' on vSwitch '{{ iscsi_b_vswitch }}'
  community.vmware.vmware_portgroup:
    hostname: '{{ inventory_hostname }}'
    username: '{{ ansible_user }}'
    password: '{{ ansible_ssh_pass }}'
    validate_certs: false
    esxi_hostname: '{{ inventory_hostname }}'
    switch: '{{ iscsi_b_vswitch }}'
    portgroup: '{{ iscsi_b_portgroup }}'
  delegate_to: localhost
  when: configure_iscsi is defined
