---
# This task configures and sets up VMware cluster

- name: VMware Cluster - Setup
  community.vmware.vmware_cluster:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: false
    datacenter_name: '{{ vcenter_dc }}'
    cluster_name: '{{ vcenter_cluster }}'

- name: VMware Cluster - Enable DRS
  community.vmware.vmware_cluster_drs:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: false
    datacenter_name: '{{ vcenter_dc }}'
    cluster_name: '{{ vcenter_cluster }}'
    enable_drs: true

- name: VMware Cluster - Enable HA
  community.vmware.vmware_cluster_ha:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: false
    datacenter_name: '{{ vcenter_dc }}'
    cluster_name: '{{ vcenter_cluster }}'
    enable_ha: true
